#!/usr/bin/env python

import sys, os, json, time
from argparse import ArgumentParser

######################
# internal functions
######################

# location of json file
bcsfilename = os.path.expanduser('~/.breadcrumbs')

# check against list of known/allowed keys
# type is not used as a key, because not guaranteed to be unique
def bcs_check_key(key):
    bcskeys = set(["num","dir","date","label"])
    if key not in bcskeys:
        raise ValueError("No key '"+key+"'")    

# check if dir arg is number or label
def bcs_num_or_label(args):
    key = None
    if args.dir is not None:
        if isinstance(args.dir,list):
            if all(d.isdigit() for d in args.dir):
                args.dir = [int(d) for d in args.dir]
                key = "num"
            elif all(not d.isdigit() for d in args.dir):
                key = "label"
            else:
                raise ValueError("Can't mix num and label in list of dirs: "+','.join(args.dir))
        else:
            if args.dir.isdigit():
                args.dir = int(args.dir)
                key = "num"
            else:
                key = "label"
    return key
        
# make dict sorted by value for specified key
def bcs_list_sort(bcslist,key):
    bcs_check_key(key)
    bcsdict = {}
    for bcsitem in bcslist:
        bcsdict[bcsitem[key]] = bcsitem
    return bcsdict
    
# resort a dict (or sort by num)
def bcs_dict_sort(bcsdict,key):
    bcs_check_key(key)
    if key=="num":
        counter = 0
        bcsdict = bcs_dict_sort(bcsdict,"date")
        for bcskey in sorted(bcsdict,reverse=True): # todo: allow reverse sort? (oldest first)
            bcsdict[counter] = bcsdict.pop(bcskey)
            counter += 1
    else:
        bcsdict = { bcsdict[bcskey][key] : bcsval for bcskey,bcsval in bcsdict.iteritems() }
    
    return bcsdict

# in case file doesn't exist or needs to be reset
def bcs_create_default_file():
    with open(bcsfilename,'w') as bcsfile:
        bcsfile.write('[]')

# load dict from file and sort
def bcs_dict_load(key="num"):
    bcs_check_key(key)
    
    if not os.path.isfile(bcsfilename):
        bcs_create_default_file()
    
    with open(bcsfilename,'r') as bcsfile:
        bcslist = json.load(bcsfile)
    
    # num is a derived key, based on date ordering
    do_num = False
    if key=="num":
        key = "date"
        do_num = True
    
    bcsdict = bcs_list_sort(bcslist,key)
        
    # replace date w/ num as key
    if do_num:
        bcsdict = bcs_dict_sort(bcsdict,"num")
        
    return bcsdict

def bcs_check_label(bcsdict,label,force):
    bcsdict = bcs_dict_sort(bcsdict,"label")
    if label in bcsdict:
        if not force:
            raise RuntimeError("Label "+label+" already in use (use -f to override)")
        else:
            # reset label to default value
            bcsdict[label]["label"] = bcsdict[label]["dir"]            

# output dict to file
def bcs_dict_dump(bcsdict):
    # convert dict back to list
    bcslist = [bcsitem[1] for bcsitem in bcsdict.iteritems()]
    with open(bcsfilename,'w') as bcsfile:
        json.dump(bcslist, bcsfile)

######################
# external functions
######################

def bcs_add(args):
    bcsdict = bcs_dict_load()
    # ensure labels are unique
    if args.label is not None:
        bcs_check_label(bcsdict,args.label,args.force)
    # add entry (use pwd by default)
    if args.dir is None:
        args.dir = os.getcwd()
    bcsdict = bcs_dict_sort(bcsdict,"dir")
    if args.dir in bcsdict and not args.force:
        print("Dir "+args.dir+" already in bcs, not updating without -f")
        return
    bcsdict[args.dir] = {
        "dir": args.dir,
        "label": args.label if args.label is not None else args.dir,
        "type": args.type if args.type is not None else "",
        "date": time.time(),
    }
    bcs_dict_dump(bcsdict)

def bcs_set(args):
    if args.dir is None:
        raise ValueError("Must specify # or label of directory")
    bcsdict = bcs_dict_load()
    # ensure labels are unique
    if args.label is not None:
        bcs_check_label(bcsdict,args.label,args.force)
    # update label and/or type
    key = bcs_num_or_label(args)
    bcsdict = bcs_dict_sort(key)
    if args.dir in bcsdict:
        if args.label is not None:
            bcsdict[num]["label"] = args.label
        if args.type is not None:
            bcsdict[num]["type"] = args.type
        bcs_dict_dump(bcsdict)
    else:
        raise ValueError("No item "+str(args.num))

def bcs_list(args):
    # for specific dir, only print name: used for "go" functionality
    if args.dir is not None:
        key = bcs_num_or_label(args)
        bcsdict = bcs_dict_load(key)
        print(bcsdict[args.dir]["dir"])
    # default: print all, w/ format (long):
    # N: dir    (date    label   type)
    else:
        bcsdict = bcs_dict_load("num")
        # if only listing nonexistent dirs, remove existent dirs from dict first
        if args.nonexistent:
            for bcskey in bcsdict.keys():
                if os.path.isdir(bcsdict[bcskey]["dir"]):
                    bcsdict.pop(bcskey)
            if len(bcsdict)==0:
                return
        # make copy w/ printable values in order
        bcsdict_rows = [[str(bcskey),
                     bcsval["dir"],
                     time.ctime(bcsval["date"]),
                     '""' if not bcsval["label"] or bcsval["label"]==bcsval["dir"] else bcsval["label"],
                     '""' if not bcsval["type"] else bcsval["type"]] for bcskey,bcsval in sorted(bcsdict.iteritems())]
        # transpose to find max length for each column
        column_lengths = [max(len(row[i]) for row in bcsdict_rows) for i in range(5)]
        for row in bcsdict_rows:
            line = ""
            line += "{0:>{1}}:".format(row[0],column_lengths[0])
            line += " {0:<{1}}".format(row[1],column_lengths[1])
            if args.long:
                line += "  {0:<{1}}".format(row[2],column_lengths[2])
                line += "  {0:<{1}}".format(row[3],column_lengths[3])
                line += "  {0:<{1}}".format(row[4],column_lengths[4])
            print(line)
    
def bcs_rm(args):
    # remove by num or label
    if len(args.dir)>0:
        if not isinstance(args.dir,list):
            args.dir = [args.dir]
        key = bcs_num_or_label(args)
        bcsdict = bcs_dict_load(key)
        for d in args.dir:
            if d in bcsdict:
                bcsdict.pop(d)
        bcs_dict_dump(bcsdict)
    # remove many by type, or any nonexistent
    elif args.type or args.nonexistent:
        bcsdict = bcs_dict_load("num")
        for bcskey in bcsdict.keys():
            bcsval = bcsdict[bcskey]
            if args.type:
                if bcsval["type"]==args.type:
                    bcsdict.pop(bcskey)
            elif args.nonexistent:
                if not os.path.isdir(bcsval["dir"]):
                    bcsdict.pop(bcskey)
        bcs_dict_dump(bcsdict)
    # remove all (clear)
    # todo: backup file by default?
    elif args.all:
        bcs_create_default_file()

######################
# main function
######################

def bcs(argv=None):
    if argv is None: argv = sys.argv[1:]
    
    # top-level parser
    parser = ArgumentParser()
    subparsers = parser.add_subparsers()
    
    # parser for add
    parser_add = subparsers.add_parser("add")
    parser_add.add_argument("dir", metavar="dir", type=str, nargs='?', help="name of directory to add (if not pwd)")
    parser_add.add_argument("-l", "--label", dest="label", type=str, help="label for directory to add (optional)")
    parser_add.add_argument("-t", "--type", dest="type", type=str, help="type for directory to add (optional)")
    parser_add.add_argument("-f", "--force", dest="force", action="store_true", help="force update of already-used label or directory")
    parser_add.set_defaults(func=bcs_add)

    # parser for set
    parser_set = subparsers.add_parser("set")
    parser_set.add_argument("dir", metavar="dir", type=str, nargs='?', help="# or label of directory to update")
    parser_set.add_argument("-l", "--label", dest="label", type=str, help="label for directory to update (optional)")
    parser_set.add_argument("-t", "--type", dest="type", type=str, help="type for directory to update (optional)")
    parser_set.add_argument("-f", "--force", dest="force", action="store_true", help="force update of already-used label")
    parser_set.set_defaults(func=bcs_set)

    # parser for list
    parser_list = subparsers.add_parser("list")
    parser_list.add_argument("dir", metavar="dir", type=str, nargs='?', help="# or label of directory to list (lists all by default)")
    parser_list.add_argument("-l", "--long", dest="long", action="store_true", help="use long listing (dates, labels, types)")
    parser_list.add_argument("-n", "--nonexistent", dest="nonexistent", action="store_true", help="list only nonexistent directories")
    parser_list.set_defaults(func=bcs_list)

    # parser for rm
    parser_rm = subparsers.add_parser("rm")
    group_rm = parser_rm.add_mutually_exclusive_group(required=True)
    group_rm.add_argument("dir", metavar="dir", type=str, nargs='*', help="#(s) or label(s) of directory(s) to remove from list", default=[])
    group_rm.add_argument("-t", "--type", dest="type", type=str, help="remove all of specified type")
    group_rm.add_argument("-n", "--nonexistent", dest="nonexistent", action="store_true", help="remove nonexistent directories")
    group_rm.add_argument("-a", "--all", dest="all", action="store_true", help="remove all")
    parser_rm.set_defaults(func=bcs_rm)

    # parse and run
    args = parser.parse_args(args=argv)
    args.func(args)

if __name__ == "__main__":
    bcs()
